name: Katalon CI

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  katalon-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Download Katalon Engine
      run: |
        wget https://download.katalon.com/11.1.1/Katalon_Studio_Engine_Linux_64-11.1.1.tar.gz
        tar -xzf Katalon_Studio_Engine_Linux_64-11.1.1.tar.gz

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgtk-3-0 libgbm1

    - name: Prepare clean workspace
      run: |
        WORKDIR=$RUNNER_TEMP/katalon-workspace
        mkdir -p $WORKDIR
        cp -r $GITHUB_WORKSPACE/* $WORKDIR
        echo "WORKDIR=$WORKDIR" >> $GITHUB_ENV

    - name: Run Katalon Test
      run: |
        cd $WORKDIR

        xvfb-run --auto-servernum ./Katalon_Studio_Engine_Linux_64-11.1.1/katalonc \
        -noSplash \
        -clean \
        -runMode=console \
        -consoleLog \
        -projectPath="$WORKDIR/tugas6-katalon.prj" \
        -retry=0 \
        -testSuitePath="Test Suites/Login" \
        -browserType="Chrome (headless)" \
        -executionProfile="default" \
        -apiKey="${{ secrets.KATALON_API_KEY }}" \
        --config -Djava.awt.headless=true

    - name: Upload Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: katalon-report
        path: Reports/
    
    - name: Prepare GitHub Pages
      run: |
        mkdir public
        find Reports -name "report.html" -exec cp {} public/index.html \;
    
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: public

  deploy-pages:
    needs: katalon-test
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4